---
- name: Create Nexus user
  ansible.builtin.user:
    name: "{{ nexus_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Create Nexus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    mode: "0775"
  loop:
    - "{{ nexus_base_dir }}"
    - "{{ nexus_data_dir }}"
    - "{{ nexus_tmp_dir }}"

- name: Download Nexus archive
  ansible.builtin.get_url:
    url: "{{ nexus_download_url }}"
    dest: "{{ nexus_tmp_dir }}/{{ nexus_archive }}"
    mode: "0664"

- name: Extract Nexus archive
  ansible.builtin.unarchive:
    src: "{{ nexus_tmp_dir }}/{{ nexus_archive }}"
    dest: "{{ nexus_base_dir }}"
    remote_src: true
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    creates: "{{ nexus_install_dir }}/bin/nexus"

- name: Create Nexus current symlink
  ansible.builtin.file:
    src: "{{ nexus_install_dir }}"
    dest: "{{ nexus_current_link }}"
    state: link
...
