---
nexus_version: "3.88.0-08"
nexus_user: nexus

nexus_base_dir: /opt/sonatype
nexus_current_link: "{{ nexus_base_dir }}/nexus"
nexus_install_dir: "{{ nexus_base_dir }}/nexus-{{ nexus_version }}"

nexus_data_dir: /data/sonatype/sonatype-work
nexus_port: "8081"
nexus_java_opts: "-Xms1200M -Xmx1200M"

nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
nexus_archive: "nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
nexus_tmp_dir: /home/ansible/tmp
...
